//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOS.App_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmployeePayments = new HashSet<EmployeePayment>();
            this.ItemPurchases = new HashSet<ItemPurchase>();
            this.EmployeeAdjustments = new HashSet<EmployeeAdjustment>();
        }
    
        public long ID { get; set; }
        public Nullable<long> HRID { get; set; }
        public string EPF { get; set; }
        public string FullName { get; set; }
        public string CallingName { get; set; }
        public Nullable<int> FactoryId { get; set; }
        public Nullable<decimal> CreditBalance { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Department { get; set; }
        public string EPFNumber { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string TnANumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePayment> EmployeePayments { get; set; }
        public virtual Factory Factory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPurchase> ItemPurchases { get; set; }
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAdjustment> EmployeeAdjustments { get; set; }
    }
}
