//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOS.App_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTransaction
    {
        public int ID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> TransactionTypeId { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
