//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOS.App_Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MPOSConStr : DbContext
    {
        public MPOSConStr()
            : base("name=MPOSConStr")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeePayment> EmployeePayments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Factory> Factories { get; set; }
        public virtual DbSet<ItemPurchase> ItemPurchases { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemTransaction> ItemTransactions { get; set; }
        public virtual DbSet<ItemType> ItemTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Metric> Metrics { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<EmployeeAdjustment> EmployeeAdjustments { get; set; }
    }
}
